{% set name = "hyp3_metadata" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e740bd0db31ccf9fe8d1fb582353ffd3a80cb5e726def19408eec19114a037cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.6
    - importlib_metadata
    - jinja2
    - gdal
    - pillow
    - python-dateutil

test:
  imports:
    - hyp3_metadata
  commands:
    - python -m hyp3_metadata --help

about:
  home: https://github.com/ASFHyP3/hyp3-metadata-templates
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Package for generating HyP3 products' metadata

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jlrine2
