{% set name = "hyp3_metadata" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19f2320f7a67a47000e5edf5123b3d87dae40c05bf229abe96ccd13967f60c71

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.6
    - importlib_metadata
    - jinja2
    - gdal
    - pillow

test:
  imports:
    - hyp3_metadata

about:
  home: https://github.com/ASFHyP3/hyp3-metadata-templates
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Package for generating HyP3 products' metadata

extra:
  recipe-maintainers:
    - jhkennedy
