{% set name = "hyp3_metadata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58abc36926874891c937289cbe0f7f1242d6facd686ef307ac0c645485a3f481

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=42
    - setuptools_scm >=3.4
    - wheel
  run:
    - python >=3.6
    - importlib_metadata
    - jinja2
    - gdal
    - pillow

test:
  imports:
    - hyp3_metadata

about:
  home: https://github.com/ASFHyP3/hyp3-metadata-templates
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Package for generating HyP3 products' metadata

extra:
  recipe-maintainers:
    - jhkennedy
    - asjohnston-asf
    - jlrine2
